# --- builder
FROM node:18-alpine AS builder
WORKDIR /app
COPY app/package*.json .
RUN npm ci --only=production
COPY app .

# --- final
FROM node:18-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app /app
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1
USER node
CMD ["node","server.js"]
