version: "3.8"
services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - webapp
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

networks:
  webnet:
